# -*- coding: utf-8 -*-
"""Calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15SsgG6v_ESsDv2waQML6hLZvEACdrfJq
"""

def calculator():
    try:
        num1 = float(input("Enter first number: "))
        operator = input("Enter operator (+, -, *, /): ")
        num2 = float(input("Enter second number: "))

        if operator == '+':
            print("Result:", num1 + num2)
        elif operator == '-':
            print("Result:", num1 - num2)
        elif operator == '*':
            print("Result:", num1 * num2)
        elif operator == '/':
            if num2 == 0:
                print("Error: Division by zero!")
            else:
                print("Result:", num1 / num2)
        else:
            print("Invalid operator!")

    except ValueError:
        print("Invalid input! Please enter numbers.")

calculator()